### ISSUE TITLE
/api/auth/login | response 데이터 추가 요청

### ISSUE THREAD

**Issue by ZZANZU** [capstoneku/android-client-normal#4]
현재는 로그인(/api/auth/login) 성공시, response로 JSON Web Token만을 리턴하고있는데,

```
1)이메일 주소 
2)닉네임
```

위의 두가지를 추가로 응답 객체에 추가해주시면 좋겠습니다. 사용 용도는 추후에 앱에 현재 로그인된 사용자에 대한 정보에 사용하기 위함입니다. (e.g. 마이페이지 내에 사용자 정보에 이메일 표시)

**Comment by cloudgray** [comment]
넵 수정하겠습니다.
``` 
data = {
  email: user.email,
  nickname: user.nickname,
  token: token
}
```
이렇게 보내드릴게요.

**Comment by ZZANZU** [comment]
<img width="326" alt="스크린샷 2019-05-22 오후 3 54 40" src="https://user-images.githubusercontent.com/26498433/58153447-f861ff80-7ca9-11e9-8043-e9c76771133f.png">

`nickname` 값 오는거 확인하였습니다.

다만, `email` 까지도 리턴해주시면 감사하겠습니다 :)

**Comment by ZZANZU** [comment]
@cloudgray 

<img width="320" alt="스크린샷 2019-05-22 오후 4 23 11" src="https://user-images.githubusercontent.com/26498433/58154984-e8e4b580-7cad-11e9-808a-ce570a588b45.png">

빠른 처리 감사드립니다 ㅎㅎ 이슈 닫겠습니다
